### ISSUE TITLE
Main panel not displaying anything

### ISSUE THREAD

**Issue by louisponet** [arohl/gdis#2]
Hi,

I'm trying to get your application working on my macbook running OSX 10.11.6, since I'd like to use it together with Quantum Espresso. I first received a compiler error since it couldn't find the library for -lGLU, but I went around that by linking the library directory for the opengl framework. Everything compiled, but when running it I got an error: Error: could not allocate colourmap. I tried bypassing this by using gdk_colormap_get_system() instead of gdk_colormap_new(...). 

The program now manages to open and with the 0.99 version I can succesfully load a .pwi file. However, the main panel does not seem to display anything and when I resize it, it doesn't seem to refresh or something. Is this due to me bypassing the whole colormap allocation thing? If so, what can I do to fix the issue? I tried to find out what's exactly wrong but since I don't really know anything about C I just can't seem to figure it out. 

Anyway thanks!

**Comment by arohl** [comment]
Hi Louis

I use macports to install gtkglext, which then makes all the dependencies and it works fine. Are you using macports?

Many thanks

  Andrew

--
Prof Andrew Rohl
Director | Curtin Institute for Computation
Professor of Computational Science | Department of Chemistry
Curtin University
PO Box U 1987
Perth, WA 6845
Ph: +61 8 9266 3124
Fax: +61 8 9266 2300
Web: http://computation.curtin.edu.au
