### ISSUE TITLE
Issues installing gtkglext

### ISSUE THREAD

**Issue by neetsaki** [arohl/gdis#32]
Hello!
Seem like it's a useful GUI for many computational chemistry softwares. However, it's very hard to compile it, especially it's dependency. It may need users have a good command of GTK+platform construct.
When I attempt to install gtkglext, there is a weird error appearing
```
gdkglfont-x11.c:21:10: fatal error: pango/pangox.h: No such file or directory
   21 | #include <pango/pangox.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```
but when I check for pango package by `pkg-config --cflags --libs gtk+-2.0` , it seems all is fine....
```
-pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype
```
This software installation is very difficulty for a student major in material science (/w\)
Hope for updating a full installation guide in detail, or a binary version with static library.

**Comment by ovhpa** [comment]
Hello @neetsaki,
Would you mind telling me which system you are trying to install GDIS?
Sorry I planned to prepare an INSTALL.txt file with more distribution-specific instruction but I've very busy lately... m(_ _)m
Best,

**Comment by neetsaki** [comment]
> Hello @neetsaki,
> Would you mind telling me which system you are trying to install GDIS?
> Sorry I planned to prepare an INSTALL.txt file with more distribution-specific instruction but I've very busy lately... m(_ _)m
> Best,

Thanks for your reply~(My system is Ubuntu 19.10)
Just now I find a auto-install pre-requisite method using apt-get command in youtube ([url](https://www.youtube.com/watch?v=pxNy6chlclw))~
```
sudo apt-get install libgtkglext1-dev
sudo apt-get install gtk+-2.0
```
and all problem have disappeared~~~
Recommend to add a note for other potential users——“never compile these pre-requisite package step by step by yourself” www
PS: It's really a useful tool for me and thanks for your "wheels" again~~

**Comment by ovhpa** [comment]
Glad my video was useful.
Have a nice time with GDIS and don't hesitate to ask if you bump into another issue ;)
Best,
