### ISSUE TITLE
The command line version no longer compiles

### ISSUE THREAD

**Issue by arohl** [arohl/gdis#42]
I had a request asking if the command line version could do a particular task. I had forgotten that we even have it! However it no longer compiles if you choose this option in the install script. Fails to link with the following errors:

Undefined symbols for architecture x86_64:
  "_dat_graph_add_y", referenced from:
      _draw_plot_band.part.0 in plots.o
      _draw_plot_energy in plots.o
      _draw_plot_force in plots.o
      _draw_plot_volume in plots.o
      _draw_plot_pressure in plots.o
      _draw_plot_dos in plots.o
      _draw_plot_bandos in plots.o
      ...
  "_dat_graph_set_limits", referenced from:
      _draw_plot_band.part.0 in plots.o
      _draw_plot_energy in plots.o
      _draw_plot_force in plots.o
      _draw_plot_volume in plots.o
      _draw_plot_pressure in plots.o
      _draw_plot_dos in plots.o
      _draw_plot_bandos in plots.o
      ...
  "_dat_graph_set_sub_title", referenced from:
      _draw_plot_bandos in plots.o
      _vasp_xml_plot_energy in file_vasp.o
      _uspex_graph_path_update in file_uspex.o
      _uspex_graph_best_update in file_uspex.o
      _read_output_uspex in file_uspex.o
  "_dat_graph_set_title", referenced from:
      _draw_plot_band.part.0 in plots.o
      _draw_plot_energy in plots.o
      _draw_plot_force in plots.o
      _draw_plot_volume in plots.o
      _draw_plot_pressure in plots.o
      _draw_plot_dos in plots.o
      _draw_plot_bandos in plots.o
      ...
  "_dat_graph_set_type", referenced from:
      _draw_plot_band.part.0 in plots.o
      _draw_plot_energy in plots.o
      _draw_plot_force in plots.o
      _draw_plot_volume in plots.o
      _draw_plot_pressure in plots.o
      _draw_plot_dos in plots.o
      _draw_plot_bandos in plots.o
      ...
  "_dat_graph_set_x", referenced from:
      _draw_plot_band.part.0 in plots.o
      _draw_plot_energy in plots.o
      _draw_plot_force in plots.o
      _draw_plot_volume in plots.o
      _draw_plot_pressure in plots.o
      _draw_plot_dos in plots.o
      _draw_plot_bandos in plots.o
      ...
  "_dat_graph_set_x_title", referenced from:
      _draw_plot_band.part.0 in plots.o
      _draw_plot_energy in plots.o
      _draw_plot_force in plots.o
      _draw_plot_volume in plots.o
      _draw_plot_pressure in plots.o
      _draw_plot_dos in plots.o
      _draw_plot_bandos in plots.o
      ...
  "_dat_graph_set_y_title", referenced from:
      _draw_plot_band.part.0 in plots.o
      _draw_plot_energy in plots.o
      _draw_plot_force in plots.o
      _draw_plot_volume in plots.o
      _draw_plot_pressure in plots.o
      _draw_plot_dos in plots.o
      _draw_plot_bandos in plots.o
      ...
  "_dat_graph_toggle_xaxis", referenced from:
      _draw_plot_band.part.0 in plots.o
      _draw_plot_bandos in plots.o
  "_dat_graph_toggle_yaxis", referenced from:
      _draw_plot_dos in plots.o
      _draw_plot_bandos in plots.o
  "_graph_reset", referenced from:
      _vasp_out_reset in file_vasp.o
  "_graph_reset_data", referenced from:
      _vasp_xml_plot_energy in file_vasp.o
      _vasp_xml_update_plot_energy in file_vasp.o
      _uspex_graph_path_update in file_uspex.o
      _uspex_graph_comp_update in file_uspex.o
      _uspex_graph_best_redo in file_uspex.o
  "_graph_set_xticks", referenced from:
      _draw_plot_band.part.0 in plots.o
      _draw_plot_energy in plots.o
      _draw_plot_force in plots.o
      _draw_plot_volume in plots.o
      _draw_plot_pressure in plots.o
      _draw_plot_dos in plots.o
      _draw_plot_bandos in plots.o

Seems to me that *plots.c* in the *makefile.src* should be after the *ifeq ($(USE_GUI), YES)*. However, it will still fail to link because there are plots in *file_vasp.c* and *file_uspex.c* @ovhpa Can the routines that plot in these files be moved to different files so that the *file_* files don't do anything guid related?

**Comment by ovhpa** [comment]
Ok, I will have a look at it this week / weekend.
I have never used the command line version, but I will see what I can do.
Hopefully it will just be a matter of adding some `#define` and moving some functions.
